### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by ghost** [HenryAlbu/Facebook-Messenger-and-Whatsapp-message-spammer#18]
I cloned this to prank my friend however I'm not sure what I did wrong. I meet the requirements that you have outlined.
This is the output on my end:
Opening Chrome
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\rukun\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\rukun\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/rukun/PycharmProjects/FB-Messenger-Whatsapp-Discord-message-spammer/app.py", line 9, in long_operation_thread
    spammer.start_spam()
  File "C:\Users\rukun\PycharmProjects\FB-Messenger-Whatsapp-Discord-message-spammer\spammer.py", line 13, in start_spam
    driver = webdriver.Chrome('chromedriver.exe')
  File "C:\Users\rukun\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\rukun\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\rukun\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\rukun\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\rukun\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81

Any help would be appreciated although I doubt you will respond:/

**Comment by ghost** [comment]
nvm i fixed it by replacing the cromedrive with the latest stable release
