### ISSUE TITLE
Error (help me lol)

### ISSUE THREAD

**Issue by whyisthesheep** [HenryAlbu/Facebook-Messenger-and-Whatsapp-message-spammer#23]
### It returns this when i try to use it on discord
```
Opening Chrome
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Username\Downloads\FB-Messenger-Whatsapp-Discord-message-spammer-master\FB-Messenger-Whatsapp-Discord-message-spammer-master\app.py", line 9, in long_operation_thread
    spammer.start_spam()
  File "C:\Users\Username\Downloads\FB-Messenger-Whatsapp-Discord-message-spammer-master\FB-Messenger-Whatsapp-Discord-message-spammer-master\spammer.py", line 13, in start_spam
    driver = webdriver.Chrome('chromedriver.exe')
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

```

**Comment by dollebrekel** [comment]
That is because the webdriver version does not match with your chrome version

**Comment by hugobder** [comment]
> That is because the webdriver version does not match with your chrome version

Thank you, I had the same error and it solved my problem !
